version: '2'
services:
    db: 
        image: mysql/mysql-server:latest
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: Instabug_Backend_Challenge_development
            MYSQL_USER: omar
            MYSQL_PASSWORD: instabug
    app: 
        entrypoint: ["sh", bin/entrypoint.sh]
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        ports: 
            - "3000:3000"
        depends_on:
            - db
        links:
            - db
        environment:
            DB_USER: omar
            DB_NAME: Instabug_Backend_Challenge_development
            DB_PASSWORD: instabug
            DB_HOST: db

